import { logger } from 'react-native-logs';
import * as FileSystem from 'expo-file-system';

const log = logger.createLogger();

const logObject = (obj: any, depth: number, maxDepth: number): string => {
    if (depth > maxDepth) return '... (truncated)';
    if (typeof obj !== 'object' || obj === null) return JSON.stringify(obj);

    let result = '{';
    for (const key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key)) {
            result += `\n${'  '.repeat(depth + 1)}${key}: ${logObject(obj[key], depth + 1, maxDepth)}`;
        }
    }
    result += `\n${'  '.repeat(depth)}}`;
    return result;
};

export const logIncomingData = (data: any, functionName: string, maxDepth: number = 3) => {
    const dataType = typeof data;
    let logMessage = `Entering function:${functionName} with data of type: ${dataType}: `;

    if (dataType === 'object' && data !== null) {
        logMessage += logObject(data, 0, maxDepth);
    } else {
        logMessage += JSON.stringify(data);
    }

    log.debug(logMessage);
};

export { log };
export const useMockData = false;

export const synonymGroups: { [key: string]: string[] } = {
    "polyamide": ["polyamide", "nylon"],
    "spandex": ["spandex", "elastane"],
    "cotton": ["cotton"],
    "100% cotton": ["100% cotton"],
    "wool": ["wool", "merino", "cashmere"],
    "silk": ["silk", "satin"],
    "leather": ["leather", "faux leather", "vegan leather"],
    "denim": ["denim", "jean"],
    "linen": ["linen", "flax"],
    "rayon": ["rayon", "viscose"],
    "polyester": ["polyester", "poly"],
    "chiffon": ["chiffon", "georgette"],
    "lace": ["lace", "embroidered lace"],
    "velvet": ["velvet", "velour"],
    "fleece": ["fleece", "polar fleece"],
    "tweed": ["tweed", "herringbone"],
    "crepe": ["crepe", "crêpe"],
    "off-the-shoulder": ["off-the-shoulder", "shoulderless", "bardot"],
    "short dress": ["short dress", "mini dress"],
    "maxi dress": ["maxi dress", "full-length dress", "floor-length dress"],
    "midi dress": ["midi dress", "calf-length dress", "tea-length dress"],
    "shift dress": ["shift dress", "straight dress"],
    "wrap dress": ["wrap dress", "surplice dress"],
    "a-line dress": ["a-line dress", "flare dress"],
    "ball gown": ["ball gown", "evening gown", "formal dress"],
    "blazer": ["blazer", "sports jacket", "suit jacket"],
    "trench coat": ["trench coat", "raincoat"],
    "bomber jacket": ["bomber jacket", "flight jacket"],
    "parka": ["parka", "anorak"],
    "jumpsuit": ["jumpsuit", "romper", "playsuit"],
    "romper": ["romper", "playsuit", "onesie"],
    "jeans": ["jeans", "denim pants"],
    "leggings": ["leggings", "stretch pants", "yoga pants"],
    "trousers": ["trousers", "pants", "slacks"],
    "cargo pants": ["cargo pants", "utility pants"],
    "shorts": ["shorts", "bermuda shorts"],
    "cargo": ["cargo"],
    "capris": ["capris", "cropped pants"],
    "skirts": ["skirts", "kilt"],
    "pencil skirt": ["pencil skirt", "fitted skirt"],
    "pleated skirt": ["pleated skirt", "accordion skirt"],
    "sweater": ["sweater", "jumper", "pullover"],
    "cardigan": ["cardigan", "button-up sweater"],
    "turtleneck": ["turtleneck", "roll neck", "polo neck"],
    "t-shirt": ["t-shirt", "tee", "shirt"],
    "tank top": ["tank top", "sleeveless top", "camisole"],
    "blouse": ["blouse", "top", "dress shirt"],
    "peacoat": ["peacoat", "pea jacket", "double-breasted coat"],
    "feathers": ["feathers", "plumes"],
    "sequins": ["sequins", "sparkles", "paillettes"],
    "rhinestones": ["rhinestones", "diamanté"],
    "ruffles": ["ruffles", "frills", "flounces"],
    "pleats": ["pleats", "folds"],
    "buttons": ["buttons", "fasteners"],
    "zippers": ["zippers", "zips", "closures"],
    "pockets": ["pockets", "compartments"],
    "belts": ["belts", "waistbands", "sashes"],
    "patchwork": ["patchwork", "quilted"],
    "embroidery": ["embroidery", "needlework"],
    "prints": ["prints", "patterns", "motifs"],
    "floral": ["floral", "flower print"],
    "animal print": ["animal print", "leopard print", "zebra print"],
    "checkered": ["checkered", "plaid", "tartan"],
    "stripes": ["stripes", "striped"],
    "polka dots": ["polka dots", "dot print", "spotted"],
    "tie-dye": ["tie-dye", "dyed"],
    "solid color": ["solid color", "plain", "monochrome"],
    "colorblock": ["colorblock", "color-blocked"],
    "metallic": ["metallic", "shiny", "glossy"],
    "matte": ["matte", "flat"],
    "sheer": ["sheer", "see-through", "transparent"],
    "opaque": ["opaque", "non-transparent"],
    "high-waisted": ["high-waisted", "high-rise"],
    "low-rise": ["low-rise", "low-waisted"],
    "mid-rise": ["mid-rise", "mid-waisted"],
    "skinny": ["skinny", "slim-fit", "tapered"],
    "bootcut": ["bootcut", "flared"],
    "wide-leg": ["wide-leg", "palazzo"],
    "cuffed": ["cuffed", "rolled-up"],
    "frayed": ["frayed", "distressed", "raw hem"],
    "v-neck": ["v-neck", "v-shaped neckline"],
    "crew neck": ["crew neck", "round neck", "circular neckline"],
    "square neck": ["square neck", "square neckline"],
    "halter": ["halter", "halter neck"],
    "strapless": ["strapless", "bandeau"],
    "long sleeve": ["long sleeve", "full sleeve"],
    "short sleeve": ["short sleeve", "half sleeve"],
    "sleeveless": ["sleeveless", "no sleeve"],
    "three-quarter sleeve": ["three-quarter sleeve", "¾ sleeve"],
    "bell sleeve": ["bell sleeve", "flared sleeve"],
    "puff sleeve": ["puff sleeve", "balloon sleeve"],
    "cropped": ["cropped", "short length"],
    "ankle-length": ["ankle-length", "cropped"],
    "floor-length": ["floor-length", "maxi-length"],
    "knee-length": ["knee-length", "midi-length"],
    "asymmetrical": ["asymmetrical", "uneven", "irregular"],
    "peplum": ["peplum", "ruffled waist"],
    "cutout": ["cutout", "open section"],
    "lace-up": ["lace-up", "corset-style"],
    "double-breasted": ["double-breasted", "two rows of buttons"],
    "single-breasted": ["single-breasted", "one row of buttons"],
    "slit": ["slit", "split"],
    "gathered": ["gathered", "ruched", "bunched"],
    "draped": ["draped", "flowing", "loose"],
    "fitted": ["fitted", "tailored", "slim-fit"],
    "oversized": ["oversized", "baggy", "loose"],
    "relaxed fit": ["relaxed fit", "casual fit"],
    "bodycon": ["bodycon", "figure-hugging", "tight-fit"],
    "athleisure": ["athleisure", "sporty", "activewear"],
    "streetwear": ["streetwear", "urban fashion", "casual wear"],
    "bohemian": ["bohemian", "boho", "hippie"],
    "vintage": ["vintage", "retro", "old-fashioned"],
    "modern": ["modern", "contemporary", "trendy"],
    "minimalist": ["minimalist", "simple", "clean"],
    "elegant": ["elegant", "sophisticated", "chic"],
    "casual": ["casual", "informal", "everyday"],
    "formal": ["formal", "dressy", "evening"],
    "business": ["business", "professional", "office wear"],
    "party": ["party", "festive", "celebration"],
    "beachwear": ["beachwear", "swimwear", "resort wear"],
    "outerwear": ["outerwear", "jackets", "coats"],
    "loungewear": ["loungewear", "homewear", "comfort wear"],
    "underwear": ["underwear", "lingerie", "intimates"],
    "accessories": ["accessories", "add-ons", "extras"],
    "footwear": ["footwear", "shoes", "boots"],
    "sneakers": ["sneakers", "trainers", "kicks"],
    "heels": ["heels", "high heels", "stilettos"],
    "flats": ["flats", "ballet flats", "loafers"],
    "sandals": ["sandals", "flip-flops", "slides"],
    "boots": ["boots", "ankle boots", "knee-high boots"],
    "handbags": ["handbags", "purses", "totes"],
    "clutches": ["clutches", "evening bags"],
    "hats": ["hats", "caps", "headwear"],
    "scarves": ["scarves", "wraps", "shawls"],
    "sunglasses": ["sunglasses", "shades", "eyewear"],
    "jewelry": ["jewelry", "accessories", "adornments"],
    "watches": ["watches", "timepieces", "chronographs"]
};

export const categoryMap: { [key: string]: string } = {
    // Materials
    "cotton": "material",
    "wool": "material",
    "silk": "material",
    "leather": "material",
    "denim": "material",
    "linen": "material",
    "rayon": "material",
    "polyester": "material",
    "spandex": "material",
    "nylon": "material",
    "cashmere": "material",
    "satin": "material",
    "suede": "material",
    "velvet": "material",
    "chiffon": "material",
    "lace": "material",
    "tweed": "material",
    "crepe": "material",
    "lyocell": "material",
    "viscose": "material",
    "elastane": "material",
    "faux leather": "material",
    "velour": "material",
    "mesh": "material",
    "fur": "material",
    "shearling": "material",
    "neoprene": "material",
    "acrylic": "material",
    "jersey": "material",

    // Styles
    "modern": "style",
    "vintage": "style",
    "elegant": "style",
    "casual": "style",
    "bohemian": "style",
    "minimalist": "style",
    "business": "style",
    "party": "style",
    "streetwear": "style",
    "athleisure": "style",
    "formal": "style",
    "beachwear": "style",
    "preppy": "style",
    "punk": "style",
    "gothic": "style",
    "grunge": "style",
    "hipster": "style",
    "urban": "style",
    "retro": "style",
    "classic": "style",
    "romantic": "style",

    // Types of clothing
    "blouse": "type",
    "shirt": "type",
    "t-shirt": "type",
    "tank top": "type",
    "sweater": "type",
    "cardigan": "type",
    "jacket": "type",
    "coat": "type",
    "trench coat": "type",
    "bomber jacket": "type",
    "parka": "type",
    "jeans": "type",
    "trousers": "type",
    "pants": "type",
    "shorts": "type",
    "leggings": "type",
    "jumpsuit": "type",
    "romper": "type",
    "dress": "type",
    "skirt": "type",
    "suit": "type",
    "blazer": "type",
    "swimsuit": "type",
    "bikini": "type",
    "one-piece": "type",
    "overalls": "type",
    "cape": "type",
    "poncho": "type",

    // Footwear
    "sneakers": "footwear",
    "heels": "footwear",
    "flats": "footwear",
    "sandals": "footwear",
    "boots": "footwear",
    "loafers": "footwear",
    "mules": "footwear",
    "espadrilles": "footwear",
    "oxfords": "footwear",
    "wedges": "footwear",
    "slippers": "footwear",
    "flip-flops": "footwear",

    // Accessories
    "jewelry": "accessory",
    "handbag": "accessory",
    "clutch": "accessory",
    "belt": "accessory",
    "scarf": "accessory",
    "hat": "accessory",
    "sunglasses": "accessory",
    "gloves": "accessory",
    "watch": "accessory",
    "tie": "accessory",
    "pocket square": "accessory",
    "bracelet": "accessory",
    "necklace": "accessory",
    "earrings": "accessory",
    "rings": "accessory",
    "wallet": "accessory",
    "backpack": "accessory",

    // Details
    "ruffles": "detail",
    "pleats": "detail",
    "buttons": "detail",
    "zippers": "detail",
    "pockets": "detail",
    "feathers": "detail",
    "sequins": "detail",
    "rhinestones": "detail",
    "embroidery": "detail",
    "lace-up": "detail",
    "frayed": "detail",
    "cutout": "detail",
    "belted": "detail",
    "cuffed": "detail",
    "distressed": "detail",
    "printed": "detail",
    "striped": "detail",
    "floral": "detail",
    "animal print": "detail",
    "solid color": "detail",
    "colorblock": "detail",
    "metallic": "detail",
    "sheer": "detail",
    "opaque": "detail",
    "slit": "detail",
    "gathered": "detail",
    "draped": "detail",
    "fitted": "detail",
    "oversized": "detail",
    "relaxed fit": "detail",
    "bodycon": "detail",
    "cropped": "detail",
    "asymmetrical": "detail",
    "high-waisted": "detail",
    "low-rise": "detail",
    "mid-rise": "detail",
    "skinny": "detail",
    "wide-leg": "detail",
    "bootcut": "detail",
    "flare": "detail",
    "puff sleeve": "detail",
    "bell sleeve": "detail",
    "three-quarter sleeve": "detail",
    "short sleeve": "detail",
    "long sleeve": "detail",
    "sleeveless": "detail",
    "strapless": "detail",
    "v-neck": "detail",
    "crew neck": "detail",
    "square neck": "detail",
    "halter": "detail",
    "off-the-shoulder": "detail",
    "double-breasted": "detail",
    "single-breasted": "detail",
    "patchwork": "detail",
    "quilted": "detail",
    "zip-up": "detail",
    "button-up": "detail",
    "hooded": "detail",
    "toggle": "detail",
    "fur trim": "detail",
    "epaulettes": "detail",
    "tassels": "detail",
    "fringe": "detail",
    "bow": "detail",
    "padded": "detail",
};

export const brandNames: string[] = [
    "Gucci", "Prada", "Nike", "Adidas", "Zara", "H&M", "Louis Vuitton", "Chanel", "Hermès",
    "Rolex", "Tiffany & Co.", "Cartier", "Versace", "Burberry", "Fendi", "Ralph Lauren", 
    "Givenchy", "Dior", "Valentino", "Dolce & Gabbana", "Balenciaga", "Yves Saint Laurent",
    "Tom Ford", "Calvin Klein", "Tommy Hilfiger", "Michael Kors", "Marc Jacobs", "Coach", 
    "Levi's", "Gap", "Old Navy", "Uniqlo", "Forever 21", "Victoria's Secret", "Reebok", 
    "Under Armour", "Lululemon", "New Balance", "Converse", "Puma", "Skechers", "Vans", 
    "Supreme", "Off-White", "Bape", "Stone Island", "Moncler", "Canada Goose", "The North Face", 
    "Patagonia", "Columbia", "Arc'teryx", "Carhartt", "Dickies", "Timberland", "Dr. Martens", 
    "UGG", "Crocs", "Birkenstock", "Steve Madden", "Aldo", "Nine West", "Jimmy Choo", 
    "Manolo Blahnik", "Christian Louboutin", "Stuart Weitzman", "Giuseppe Zanotti", 
    "Alexander McQueen", "Balmain", "Saint Laurent", "Kenzo", "Loewe", "Chloé", 
    "Miu Miu", "Salvatore Ferragamo", "Ermenegildo Zegna", "Brunello Cucinelli", 
    "Canali", "Kiton", "Hugo Boss", "Paul Smith", "Ted Baker", "Benetton", 
    "Diesel", "Wrangler", "Lee", "G-Star Raw", "True Religion", "Abercrombie & Fitch", 
    "Hollister", "American Eagle", "Aéropostale", "Banana Republic", "J.Crew", 
    "Ann Taylor", "Loft", "Anthropologie", "Free People", "Urban Outfitters", 
    "Lacoste", "Fred Perry", "Lyle & Scott", "Adolfo Dominguez", "Mango", 
    "Massimo Dutti", "Pull & Bear", "Stradivarius", "Bershka", "Desigual", 
    "Superdry", "Gant", "Jack & Jones", "Pepe Jeans", "River Island", 
    "Topshop", "Topman", "Missguided", "Boohoo", "ASOS", "PrettyLittleThing", 
    "Nasty Gal", "Revolve", "Zalando", "Boden", "Reiss", "AllSaints", 
    "Ted Baker", "Barbour", "Belstaff", "Hobbs", "Whistles", "Karen Millen", 
    "Phase Eight", "Warehouse", "Oasis", "Coast", "Monsoon", "Dorothy Perkins", 
    "Wallis", "Simply Be", "Evans", "Yours Clothing", "New Look", "Primark", 
    "Matalan", "George at Asda", "F&F at Tesco", "Marks & Spencer", "John Lewis", 
    "Debenhams", "House of Fraser", "Harrods", "Selfridges", "Fenwick", 
    "Liberty", "Harvey Nichols", "Saks Fifth Avenue", "Neiman Marcus", 
    "Bloomingdale's", "Macy's", "Nordstrom", "Barneys New York", "Bergdorf Goodman", 
    "Lord & Taylor", "Dillard's", "Kohl's", "JCPenney", "Sears", "Belk", 
    "Boscov's", "Bon-Ton", "Target", "Walmart", "Kmart", "TJ Maxx", 
    "Marshalls", "Ross", "Burlington", "Nordstrom Rack", "Neiman Marcus Last Call", 
    "Saks Off 5th", "Outlet", "Farfetch", "Mytheresa", "Net-a-Porter", 
    "Mr Porter", "MatchesFashion", "YOOX", "SSENSE", "LuisaViaRoma", 
    "24S", "Stylebop", "The Outnet", "Vestiaire Collective", "Gilt", 
    "Rue La La", "HauteLook", "Shopbop", "East Dane", "Amazon Fashion", 
    "Zappos", "Bluefly", "Shoes.com", "Overstock", "Rakuten", "eBay", 
    "Alibaba", "AliExpress"
];


